files: \.(md|py|txt|yaml)$
default_stages: [commit, manual]
repos:

-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.5.2
    hooks:
    - id: ruff
      args: [
      --fix,
      --unsafe-fixes,
      --exit-non-zero-on-fix,
      --target-version, "py313",
      --select, "ALL",
      --ignore, "ANN,C90,D,E501,FBT,PLR091,S101,S113,T20,CPY,DOC"
      ]
    - id: ruff-format

-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
    - id: trailing-whitespace
      args: [--markdown-linebreak-ext=md]
    - id: end-of-file-fixer
    - id: requirements-txt-fixer


-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.10.1
    hooks:
    - id: mypy
      additional_dependencies: [types-requests]
      stages: [manual]

-   repo: https://github.com/dosisod/refurb
    rev: v2.0.0
    hooks:
    - id: refurb
      args: [--python-version, "3.12"]
      stages: [manual]
