[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"

[project]
name = "safety_checker"
version = 0.1
dependencies = [
    "Pillow",
    "diffusers",
    "tqdm",
    "transformers",
]
