[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"

[project]
name = "safety_checker"
dynamic = ["dependencies"]

[tool.setuptools.dynamic]
dependencies = {file = ["requirements.txt"]}
